---
title: "Lunch and Learn Webinar Schedule"
description: |
  A regularly updated schedule of Lunch and Learn Webinars for R users at Nelson\\Nygaard.
author:
  - name: Bryan Blanc
date: "Updated as of `r strftime(Sys.Date(),'%B %d, %Y')`"
output:
  distill::distill_article:
    self_contained: false
---

Below is a regularly updated list of the upcoming scheduled Lunch and Learn webinars for R users at Nelson\\Nygaard. Until such a time as we decided to change the time slot, these will be scheduled in perpetuity from 12 - 1 p.m. Pacific time on Wednesdays on a bi-weekly basis. Refer to the table below for specific dates and topics. Occasionally, if Bryan has an especially busy project load, is taking vacation, there is an intersecting NN holiday, or there is a lack of topics, these will be canceled or moved. Advanced notice will be provided for these occasions.  Please provide feedback on the schedule if you would like a topic scheduled sooner or would like to add additional topics by contacting [Bryan directly](mailto:bblanc@nelsonnygaard.com).

```{r, echo = FALSE, out.width=1200}
library(googlesheets4)
library(googledrive)
library(tidyverse)
library(DT)

current_date = Sys.Date()

gs4_auth(email = 'bryanpblanc@gmail.com')
raw_schedule = as_id('https://docs.google.com/spreadsheets/d/1FlUvEhTikxxnQYV5CP1T4M5wgudnZJ88f4T44C9RSpc/edit?usp=sharing') %>%
  read_sheet('Webinar Sessions')  

raw_schedule %>%
  filter(Date >= Sys.Date()) %>%
  select(Date,`Session ID`,Topic) %>%
  filter(!is.na(Topic)) %>%
  mutate(Date = as.Date(Date)) %>%
  DT::datatable(rownames=FALSE, escape=FALSE,
          options = list(paging=FALSE,info=FALSE,autoWidth=TRUE), filter = 'top')
```


