library(tidyverse)
library(httr)
library(rvest)
library(janitor)
library(shiny)
library(shinydashboard)
library(tigris)
library(rnaturalearth)
library(sf)
library(shinyBS)
library(leaflet)
library(shinyWidgets)
library(DT)
library(scales)
library(ggforce)
library(tidytext)
library(rgeos)

us_states = states()
world_countries = ne_countries() %>%
  st_as_sf() %>%
  select(gu_a3,admin,region_wb,region_un,subregion,continent,geometry)

#setwd('C:/Users/blancb/OneDrive - Perkins and Will/Documents/Internal/R Training/nn_r_training/topics_setup/06_shiny_3/training_app')
#setwd('C:/Users/blancb/OneDrive - Perkins and Will/Documents/Internal/R Training/nn_r_training/')
