---
title: "R Software Versions and Users"
description: |
  A regularly updated list of R Software Versions and Users at Nelson\\Nygaard.
author:
  - name: Bryan Blanc
date: "Updated as of `r strftime(Sys.Date(),'%B %d, %Y')`"
output:
  distill::distill_article:
    self_contained: false
---

This page is a regularly updated list of R software versions and users at Nelson\\Nygaard. The lists are maintained to easily track:  

1. Which software versions are the current recommended versions 
2. which users have up to date software versions
3. Any other user specific information

# Software Versions

Below are the current recommended versions for the NN recommended R software bundle. 

| Software           | Recommended Version   | Download Link                                      |
|--------------------|-----------------------|----------------------------------------------------|
| R                  | 4.0.3                 | https://www.r-project.org/                         |
| RStudio            | 1.4.1103              | https://www.rstudio.com/products/rstudio/download/ |
| RTools             | 4.0.0                 | https://cran.r-project.org/bin/windows/Rtools/     |
| Git                | 2.30.0                | https://git-scm.com/download/win                   |

# R Users

The below is a list of the known R users at Nelson\\Nygaard. This list is used to maintain information on software versions, knowledge/skill levels, and to maintain a central repository for R work requests. If you don't see yourself on this list and want to be added, if any information is incorrect/needs to be updated, or you want to add an additional field, please [add comments to the Google sheet where this information is drawn from](https://docs.google.com/spreadsheets/d/1FlUvEhTikxxnQYV5CP1T4M5wgudnZJ88f4T44C9RSpc/edit?usp=sharing) or [contact Bryan](mailto:bblanc@nelsonnygaard.com).

```{r, echo = FALSE, out.width=1200}
library(googlesheets4)
library(googledrive)
library(tidyverse)
library(DT)

gs4_auth(email = 'bryanpblanc@gmail.com')
raw_users = as_id('https://docs.google.com/spreadsheets/d/1FlUvEhTikxxnQYV5CP1T4M5wgudnZJ88f4T44C9RSpc/edit?usp=sharing') %>%
  read_sheet('R Users') %>%
  select(-`R Skill Description`) 

raw_users %>%
  filter(`R Version` != '0.0.0') %>%
  mutate(`R Tools Version` = as.character(`R Tools Version`)) %>%
  mutate(`Email Address` = paste0("<a href='mailto:",`Email Address`,"'>",`Email Address`,"</a>")) %>%
  DT::datatable(rownames=FALSE, escape=FALSE,
          options = list(paging=FALSE,info=FALSE,autoWidth=TRUE), filter = 'top',
          width = 1200)
```

