---
title: "R Setup at Nelson\\\\Nygaard"
author: "Esther Needham, Oren Eshel, and Paul Leitman"
date: "7/29/2020"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

[Back to overview](../index.html)

# Script Management

## Folder Conventions

- Create R folder within G: Drive 
  - Talk to GIS team about adding this to the template (Oren to discuss) 
- Folder structure 
  - README.txt 
    - Title block for code with author, date, purpose 
  - Add shortcuts to P - Analysis 
  - Esther suggests three subfolders: 
    - Raw: shortcuts to G - z.orig 
    - Interim 
    - Output: shortcut to P – Graphics or SharePoint – Graphics folders 
- Start using R Projects? 
  - Allows relative file paths 
  
## Script Titleblock Snippet

In R studio go to Tools -> global options --> code --> bottom of page "edit snippets" --> scroll to bottom and paste the below in, change your name in the Author field.

```{r, eval=FALSE}
snippet header
	## ---------------------------
	##
	## Script name: 
	##
	## Purpose of script:
	##
	## Project Name: 
	##
	## Project Number: 
	##
	## Author: Esther Needham
	##
	## Date Created: `r paste(Sys.Date())`
	##
	## ---------------------------
	##
	## Notes:
	##   
	##
	## ---------------------------
	## set working directory here or make sure there is a .Rproj file
	## ---------------------------
	options(scipen = 6, digits = 4) # view outputs in non-scientific notation
	## ---------------------------
	## load up the packages we will need:  (uncomment as required)
	require(tidyverse)
	require(sf)
	## ---------------------------
	## load up functions from other scripts into memory
	# source("functions/summarise_data.R") #example
	## ---------------------------
```

  
## GitHub

- Version control and cloud storage for collaboration 
- Enterprise PW account 
  - Create your own personal github account; recommend setting up using your personal e-mail
  - Email [Joel Register](mailto:joel.register@perkinswill.com) your github username and ask to be added to the Nelson\Nygaard team 
    - “Could I request to join the enterprise GitHub account? My username is XXXXX.”  
  - Uses Git; Esther suggests using command-line 
  - Integration with RStudio also an option 
  - Follow up brownbag (Esther action?) 
  - 3/25/2020: Esther has developed resources; see PPT file and Wiki page 
  
## ShinyApps Web Hosting

### Management Dashboard

- [https://www.shinyapps.io/admin/#/profile](https://www.shinyapps.io/admin/#/profile)

### Management Account

- shinyapps@nelsonnygaard.com
- This account is accessible to various people (Bryan, Tomoko, Esther, Oren)
- You can add it to your email by: 
  - Outlook -> Accounting Settings 
  - Email Tab -> New 
  - Enter shinyapps@nelsonnygaard.com -> Next 
  - Restart Outlook and you should see the mailbox at the bottom of the left navigation toolbar. 
- Email is also forwarded to each of the above individuals. Forwarding is set up using a server side rule by logging into Outlook 365 web mail. If others need to be added, this can be done by: 
  - Log into [Outlook 365](https://outlook.office.com/mail/shinyapps@nelsonnygaard.com/inbox) (this link should take you straight to the account) 
    - If not, go to icon in upper right -> Open Another Mailbox -> Shinyapps@nelsonygaard.com 
  - Settings icon in upper right of Outlook 
  - Mail settings -> Rules 
  - “Shinyapps Email Forwarding” Rule -> Edit Rule 
  
#### Password

- Oren requested that this account be added to Okta, which hopefully can then be used to save our password. 

#### Uploading to shinyapps.io

- Use rsconnect package in RStudio to deploy using a token in the Shiny dashboard 
- In Shiny Dashboard, go to Account -> tokens -> Show -> Copy to Clipboard 
- One-time: paste the commend from the Shiny Dashboard – rsconnect::setaccount…  
- In RStudio, run: rsconnect::deployApp() 
- Set working directory to where Shiny app lives 
- Setwd… (may need to comment and uncomment) 

#### AWS SQL Server Hosting

- How do we charge costs do a credit card? Bryan needs to hook in a credit card for this.  

#### Google API Access

- Individual accounts needed, threshold beyond (~2500 per day) which you are billed per query 
- Action: re-investigate central account/billing – Oren and/or Tomoko 